
name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  - cron: "0 2 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
    
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install libsecp256k1
        run: git clone https://github.com/bitcoin-core/secp256k1 && cd secp256k1 && ./autogen.sh && ./configure --enable-module-recovery && make && make check && sudo make install
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec     
